// Build catalog/: one machine-readable index of everything in the design system,
// for developers and tools. Every path is relative to the repo root.
//
//   node scripts/build-catalog.mjs
//
// catalog/index.json      pages (per viewport: HTML, screenshot, size, sections), flows,
//                         components, assets, tokens and the Storybook kit
// catalog/flows/<id>.json one file per end-to-end flow, each step with its page HTML
// docs/FLOWS.md           the same flows as a readable list with links
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';

const read = async (f) => JSON.parse(await readFile(f, 'utf8'));
const data = await read('prototype/data.json');
const components = await read('components/index.json');
const assets = await read('assets/index.json');
const rel = (p) => p?.replace(/^\.\.\//, '');

// Pages: one entry per page id, with each viewport it was captured at.
const groupOf = {};
for (const g of data.groups) for (const p of g.pages) groupOf[p.id] = g.name;
const pages = {};
for (const s of Object.values(data.pages)) {
  const p = pages[s.id] ??= {
    id: s.id, title: s.title, group: groupOf[s.id], source: s.kit ? 'design-kit' : 'capture',
    liveUrl: s.url, state: s.overlay ? 'overlay' : s.scrolled ? 'scrolled' : 'page', viewports: {},
  };
  p.viewports[s.vp] = {
    html: rel(s.html), screenshot: rel(s.image) ?? null, width: s.width, height: s.height,
    links: s.hotspots.length,
    sections: s.sections.map((sec) => ({
      name: sec.name, x: sec.x, y: sec.y, width: sec.width, height: sec.height,
      ...(sec.html ? { html: rel(sec.html), screenshot: rel(sec.image) } : { selector: sec.selector }),
    })),
  };
}

const flows = data.flows.map((f) => ({
  id: f.id, title: f.title, source: f.kit ? 'design-kit' : 'capture',
  steps: f.steps.map((st, i) => ({
    step: i + 1, page: st.page, title: pages[st.page]?.title ?? st.page, caption: st.caption, next: st.next ?? null,
    desktop: pages[st.page]?.viewports.desktop?.html ?? null, mobile: pages[st.page]?.viewports.mobile?.html ?? null,
  })),
}));

const catalog = {
  name: 'OLX Pakistan design system',
  source: data.source,
  generated: new Date().toISOString().slice(0, 10),
  tokens: {
    json: 'tokens/tokens.json', css: 'css/tokens.css',
    kit: { json: 'storybook/tokens/tokens.json', css: 'storybook/css/tokens.css', components: 'storybook/css/components.css', entry: 'storybook/css/olx.css' },
  },
  storybook: { dir: 'storybook', components: 'storybook/src/components', patterns: 'storybook/src/patterns', templates: 'storybook/design-kit/templates/templates.json' },
  counts: {
    pages: Object.keys(pages).length, captures: Object.keys(data.pages).length, flows: flows.length,
    sections: Object.values(data.pages).reduce((n, s) => n + s.sections.length, 0),
    components: new Set(components.components.map((c) => c.name)).size, assets: assets.assets.length,
  },
  pages: Object.values(pages),
  flows,
  components: components.components.map((c) => ({
    name: c.name, viewport: c.viewport, state: c.state ?? 'default', page: c.page,
    html: c.markup ?? `components/${c.name}/${c.viewport}.html`, screenshot: c.png ?? `components/${c.name}/${c.viewport}.png`,
    width: c.width, height: c.height,
  })),
  assets: { index: 'assets/index.json', byKind: Object.fromEntries([...new Set(assets.assets.map((a) => a.kind))].map((k) => [k, assets.assets.filter((a) => a.kind === k).length])) },
};

await rm('catalog', { recursive: true, force: true });
await mkdir('catalog/flows', { recursive: true });
await writeFile('catalog/index.json', JSON.stringify(catalog, null, 1) + '\n');
for (const f of flows) await writeFile(`catalog/flows/${f.id}.json`, JSON.stringify(f, null, 1) + '\n');

// A readable list of the flows, linking each step's HTML.
const link = (p) => (p ? `[HTML](../${p})` : '–');
let md = `# End-to-end flows\n\nGenerated by \`node scripts/build-catalog.mjs\` from \`prototype/data.json\`. Each flow is also in \`catalog/flows/<id>.json\`; open any of them step by step in the prototype (\`npm run prototype\`, then Flows).\n\n`;
for (const f of flows) {
  md += `## ${f.title}\n\n\`${f.id}\` · ${f.steps.length} steps · ${f.source === 'design-kit' ? 'design kit (storybook/)' : 'captured from olx.com.pk'}\n\n| # | Page | What happens | Next | Desktop | Mobile |\n|---|---|---|---|---|---|\n`;
  for (const st of f.steps) md += `| ${st.step} | ${st.title} | ${st.caption ?? ''} | ${st.next ?? ''} | ${link(st.desktop)} | ${link(st.mobile)} |\n`;
  md += '\n';
}
await writeFile('docs/FLOWS.md', md);
console.log(`catalog/index.json: ${catalog.counts.pages} pages (${catalog.counts.captures} captures), ${flows.length} flows, ${catalog.counts.sections} sections, ${catalog.counts.components} components, ${catalog.counts.assets} assets`);
