// Generates css/tokens.css and dist/tokens.js from tokens/tokens.json.
// Usage: node scripts/build-tokens.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));

// Resolve "{color.petrol.900}" style references against the token tree.
function resolve(value, seen = []) {
  if (typeof value !== 'string') return value;
  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return value;
  const path = match[1];
  if (seen.includes(path)) throw new Error(`Circular token reference: ${[...seen, path].join(' -> ')}`);
  const target = path.split('.').reduce((node, key) => node?.[key], tokens);
  if (target === undefined) throw new Error(`Unknown token reference: {${path}}`);
  return resolve(target, [...seen, path]);
}

// Flatten a nested object into [["color-petrol-900", "#002f34"], ...].
function flatten(node, prefix = []) {
  return Object.entries(node).flatMap(([key, value]) =>
    typeof value === 'object' ? flatten(value, [...prefix, key]) : [[[...prefix, key].join('-'), resolve(value)]]
  );
}

const { semantic, breakpoint, ...primitives } = tokens;
const decl = (pairs, indent = '  ') => pairs.map(([name, value]) => `${indent}--olx-${name}: ${value};`).join('\n');

const css = `/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */

:root {
${decl(flatten(primitives))}

${decl(flatten(semantic.light))}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${decl(flatten(semantic.dark), '    ')}
  }
}

:root[data-theme="dark"] {
${decl(flatten(semantic.dark))}
}

/* Breakpoints (CSS variables can't be used in media queries; use these values directly):
${flatten(breakpoint).map(([k, v]) => ` *   ${k}: ${v}`).join('\n')}
 */
`;

const resolvedTree = (node) =>
  Object.fromEntries(Object.entries(node).map(([k, v]) => [k, typeof v === 'object' ? resolvedTree(v) : resolve(v)]));

const js = `// Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand.
export const tokens = ${JSON.stringify(resolvedTree(tokens), null, 2)};
export default tokens;
`;

mkdirSync(join(root, 'css'), { recursive: true });
mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'css/tokens.css'), css);
writeFileSync(join(root, 'dist/tokens.js'), js);
console.log('Wrote css/tokens.css and dist/tokens.js');
